INSERT INTO products (name, category, description, price, image_url, badge, stock) VALUES
('Kota Meals', 'Meals', 'Thrown Kota, Chips, Coca-Cola 440ml', 90, '/Menus/KotaMeal.png', 'Bestseller', 100),
('Burger Meals', 'Meals', 'Burger, Chips, Coca-Cola 440ml', 100, '/Menus/BurgerMeal.png', 'Special', 100),
('Chicken Meals', 'Meals', '1/4 Chicken, Bun, Chips, Coca-Cola 440ml', 80, '/Menus/ChickenMeal.png', NULL, 100),
('Fish Meals', 'Meals', 'Fish, Chips, Coca-Cola 440ml', 80, '/Menus/FishMeal.png', 'New', 100),
('Smash Kota Meals', 'Kota Meals', 'Smash Kota, Chips, Coca-Cola 440ml', 70, '/Menus/KotaMeal.png', NULL, 100),
('Smash Kota Single Meals', 'Kota Meals', 'Smash Kota, Chips', 70, '/Menus/Kota.jpg', NULL, 100),
('Double Smash Kota Meals', 'Kota Meals', 'Double Smash Kota, Chips, Coca-Cola 440ml', 70, '/Menus/KotaMeal.png', NULL, 100),
('Double Smash Kota Single Meals', 'Kota Meals', 'Double Smash Kota, Chips', 70, '/Menus/Kota.jpg', NULL, 100),
('Thrown Kota Meals', 'Kota Meals', 'Thrown Kota, Chips, Coca-Cola 440ml', 70, '/Menus/KotaMeal.png', NULL, 100),
('Thrown Kota Single Meals', 'Kota Meals', 'Thrown Kota, Chips', 70, '/Menus/Kota.jpg', NULL, 100),
('Smash Kota', 'Kota', 'Bread, Chips, Polony, Archaar, Rasaian, Egg, Lettuce', 30, '/Menus/Kota.png', NULL, 100),
('Double Smash Kota', 'Kota', 'Bread, Chips, Polony, Archaar, Rasaian, Egg, Lettuce, Cheese', 35, '/Menus/Kota.png', NULL, 100),
('Thrown Kota', 'Kota', 'Bread, Chips, Polony, Archaar, Rasaian, Egg, Lettuce, Cheese, Patty', 55, '/Menus/Kota.png', NULL, 100),
('Small Chips', 'Chips', '5cm × 5cm × 2.5cm Box', 25, '/Menus/Chips.png', NULL, 100),
('Medium Chips', 'Chips', '5cm × 7cm × 2.5cm Box', 35, '/Menus/Chips.png', NULL, 100),
('Large Chips', 'Chips', '8cm × 5cm × 3cm Box', 50, '/Menus/Chips.png', NULL, 100),
('Coca-Cola', 'Beverages', 'Coca-cola 1.25L, Coca-cola 400ml', 15, '/Menus/Coca-Cola.png', NULL, 100),
('Mocktails', 'Beverages', 'flavour Mocktails, flavour Mocktails, flavour Mocktails', 40, NULL, NULL, 100),
('Still Water', 'Beverages', 'Still Water 500ml', 7, NULL, NULL, 100),
('Still Water', 'Beverages', 'Still Water 1L', 12, NULL, NULL, 100),
('Cappy', 'Beverages', 'Pineapple flavour', 14, '/Menus/Cappy.png', NULL, 100),
('Chicken and BBQ Pizza', 'Pizza', 'A savory pizza with tender chicken and rich BBQ sauce.', 85, '/Menus/ChickenAndBBQ.png', 'Fan-favorite', 100),
('Chicken and Mayo Pizza', 'Pizza', 'Creamy and delicious, topped with chicken and mayonnaise.', 85, '/Menus/ChickenAndMayo.png', NULL, 100),
('Sweet Chilli Sausage Pizza', 'Pizza', 'A perfect blend of sweet and spicy with sausage toppings.', 90, '/Menus/mexicanChilli.png', NULL, 100),
('Pineapple Pizza', 'Pizza', 'A tropical delight with juicy pineapple chunks.', 80, '/Menus/Pineapply.png', NULL, 100),
('Mexican Chilli Pizza', 'Pizza', 'Spicy and flavorful, with authentic Mexican chilli.', 95, '/Menus/mexicanChilli.png', 'Spicy', 100);
